export const STAGE_INFO = [
  {
    num: 1,
    name: "Product Demo",
    duration: "~1 day",
    owner: "Sales / account lead",
    summary: "Show the system to the clerk of court and key staff. Walk through filer experience, clerk review, judge routing, and payments.",
    gate: "Customer champion confirmed, clerk of court approval, fee schedule documented, judge roster reviewed.",
  },
  {
    num: 2,
    name: "Clerk Training",
    duration: "~2 days",
    owner: "Implementation / support lead",
    summary: "Hands-on training for all clerk staff. Cover acceptance, rejection, judge routing, stamps, fees, and notifications in training environment.",
    gate: "All clerks trained, each completes 5+ practice filings, parish settings configured, training sign-off from champion.",
  },
  {
    num: 3,
    name: "Valpay Setup",
    duration: "3\u20135 days (parallel with 1\u20132)",
    owner: "Engineering + Valpay",
    summary: "Provision and connect the parish\u2019s merchant account through Valpay/Adyen for real payment processing.",
    gate: "Merchant account connected, test transaction succeeds (charge + refund), fee schedule loaded with zero discrepancies.",
  },
  {
    num: 4,
    name: "Staging QA",
    duration: "~3 days",
    owner: "Engineering + customer champion",
    summary: "Test 50 real-world documents on staging. Exercise the full workflow with realistic filing types specific to this parish.",
    gate: "50 docs processed end-to-end, fee accuracy 100%, stamps correct, zero critical bugs, QA sign-off.",
  },
  {
    num: 5,
    name: "Single-Filer Pilot",
    duration: "3\u20135 days",
    owner: "Customer champion + support",
    summary: "One cooperative law firm goes live on production with real filings and real money. First real legal documents for this parish.",
    gate: "20+ real filings completed, 0 payment errors, notifications working, pilot sign-off from filer and champion.",
  },
  {
    num: 6,
    name: "Graduated Rollout",
    duration: "5\u20137 days",
    owner: "Engineering + customer champion",
    summary: "Expand from 1 filer to full parish. Tybera traffic migrates incrementally: 5 filers \u2192 25% \u2192 50% \u2192 100%, each with a soak period.",
    gate: "Zero payment failures, volume tracking against expected rate, champion green-lights each step.",
  },
  {
    num: 7,
    name: "Tybera Churn",
    duration: "Target date per parish",
    owner: "Account lead",
    summary: "100% of parish filing traffic on our platform. Tybera access decommissioned. Parish moves to ongoing support.",
    gate: "100% traffic for 3+ consecutive days, Tybera decommissioned, champion signs off, parish marked Live.",
  },
];
